### ISSUE TITLE
platform compatibility with Windows

### ISSUE THREAD

**Issue by xemoka** [nuxt-community/nuxtent#17] opened 2017-07-21 19:20 UTC
Hello, I'm quite interested in what you're developing here, it's been on my list as well—not nearly as robust as what could come from this. 

My problem is I can't seem to get it running anywhere _[for future readers, it does operate fine on MacOS]_. Either following your help documentation, using the 'examples' (after updating them to match the documentation), the 'docs', or using the nuxtent-starter quick-start (`vue-cli init ...`, `npm install`, then `npm run dev`). 

I'm mainly focusing on the `dev` server, but also cannot get it running under `build` then `start`. 

I cannot navigate between pages on either Linux or Windows, however on Linux if I get the SSR page directly it will load. There appears to be no error messages outputted. 

Do you have a working example that I can tease out or perhaps there's something I'm missing?

_[Note to future readers: both Linux and MacOS will work, as things are currently coded (17-07-21) you must load the dev server from `localhost:3000` to avoid CORS errors as the content-api is loaded from local host, not 127.0.0.1]_

**Comment by alidcastano** [comment] 2017-07-21 19:33
Weird... I JUST updated the documentation and examples. How recently did you test it?

**Comment by alidcastano** [comment] 2017-07-21 19:42
If the problem is the navigation then you might be using the wrong baseURL.


Make sure you set this appropriately: 

```
module.exports = {
  api: {
    baseURL: (isProd) => isProd ? 'http://localhost:3000' : 'http://localhost:3000'
  }
}

```

**Comment by alidcastano** [comment] 2017-07-21 19:46
You can also go to the endpoint using the 'http://localhost:3000'/content-api/' path, it should show you JSON of appropriate content data.

For example: 
If you're using 'content/posts' registered directory then  'http://localhost:3000'/content-api/posts' should show you all posts data.

**Comment by xemoka** [comment] 2017-07-21 19:49
15 minutes ago. I see you updated the examples, just pulled down the new examples and tried a run on the _markdown-components_ and _multiple-content-types_. On Windows, MacOS & Linux I initially get:

> `[nuxt] Module [@nuxtjs/axios,[object Object]] should export a function`

I can correct this by replacing the pinned nuxt version with `latest`, but results in still having the navigation problem. SSR still works on Linux, not on windows.

Testing it on a MacOS machine, it works perfectly (aside from the Nuxt version problem). It looks like there could be a platform issue?

**Comment by xemoka** [comment] 2017-07-21 19:51
The _content-api_ loads fine on all platforms.

**Comment by alidcastano** [comment] 2017-07-21 20:00
Yeah, I've unfortunately only had the chance to test it on Mac.

So to be clear: with updated examples:  
- It works on Linux.
- On Windows SSR doesn't work, but you still see the data when you go to the appropriate `content-api` endpoint.

Is there really no error messages - either in the inspector or in the terminal?

**Comment by xemoka** [comment] 2017-07-21 20:06
With updated examples,
* Linux only provides SSR pages, hydration (is that the correct term?) does not work; you must type / manually navigate to the page url
* On windows both SSR and navigation does not work. 
* On both Linux and Windows the content-api appears functional. 

On Linux, the JS console spits out the following on navigation:
```
(index):1 XMLHttpRequest cannot load http://localhost:3000/content-api/hello-world. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:3000' is therefore not allowed access.
createError.js:16 

Uncaught (in promise) Error: Network Error
    at createError (createError.js:16)
    at XMLHttpRequest.handleError (xhr.js:87)
```
There are no console errors on SSR load, and just a 404 in windows

**Comment by xemoka** [comment] 2017-07-21 20:11
Well, that last error on Linux is avoidable with CORS setup. 

So at least there's that found out. I'm not sure why MacOS doesn't have the same problem...

**Comment by alidcastano** [comment] 2017-07-21 20:21
Good to know that at least something works 😅

Ok, so let's narrow this down: 


Hydration issue I'm aware of. If you're referring to `incorrect HTML markup error`. I opened up seperate [issue](https://github.com/nuxt-community/nuxtent/issues/150) for that. Problem seems to be with JSX rendering HTML because if you use `v-html` directive, the error goes away. But ideally, I need JSX so that users can just use `nuxtent-body` for both markdown HTML and components. So let's just say that Linux "works".


The problem is that SRR and client side routing don't work... It seems to be a problem with axios request (maybe a `@nuxtjs/axios` module problem?), since you can navigate to `content-api` endpoint without a problem.

**Comment by alidcastano** [comment] 2017-07-21 20:31
Unfortunately, I don't have a windows computer to test this out -- can you try fetching from that same endpoint on your own (without the `app.$content` helper) and see if that works?

**Comment by xemoka** [comment] 2017-07-21 20:40
On windows it returns a 404 when manually entering the page, perhaps it's encountering a problem even before rendering?

I wish I understood more about Nuxt's routing—and how it interfaces with Nuxtent... still working on that myself.

**Comment by xemoka** [comment] 2017-07-21 20:53
Further hammering:

The user is presented a 127.0.0.1 url from webpack's dev server to load in the browser. The `content-api` is being loaded from localhost; this results in CORS problems, and stops navigation. This is valid for box MacOS an Linux. I was loading manually from localhost when testing MacOS. 

This can be solved by either always using 127.0.0.1 or localhost throughout -> I'm not sure how to get webpack to show localhost instead of 127.0.0.1 when it loads up the dev server. 

---

This doesn't solve the windows problem. There are problems with both SSR and navigation, with either 127.0.0.1 and localhost.

**Comment by alidcastano** [comment] 2017-07-21 21:01
Yea, `Nuxtent` sends a 404 is sent if the `content-api` endpoint doesn't exist, which would happen with different base URLs. (see https://github.com/nuxt-community/nuxtent/blob/master/lib/core/api.js#L32)

We probably just need to configure `axios` appropriately to solve the CORS problem. (see https://github.com/nuxt-community/nuxtent/blob/master/lib/module.js#L100)

Right now I'm only providing a server and browser API endpoint, not handling CORS problems.

**Comment by alidcastano** [comment] 2017-07-21 21:17
From [axios](https://github.com/nuxt-community/modules/tree/master/modules/axios) module readme: 
```
If browserBaseURL is not provided it defaults to baseURL value.
If hostname & port of browserbaseURL are equal to nuxt server, it defaults to relative part of baseURL. So if your nuxt application is being accessed under a different domain, requests go to same origin and prevents Cross-Origin problems.
```
Which is weird since both of them should point to same  host and port... only thing being changed is prefix.

**Comment by xemoka** [comment] 2017-07-21 21:52
I think a solution for the CORS issue is to use `127.0.0.1` as the final host option instead of `localhost` ( https://github.com/nuxt-community/nuxtent/blob/master/lib/module.js#L9 ). That way everything lines up as expected if you don't have `process.env.HOST` set. 

Still trying to figure out the windows glitch.

**Comment by alidcastano** [comment] 2017-07-21 21:56
But the axios module uses the same fallback `https://github.com/nuxt-community/modules/blob/master/modules/axios/index.js#L7`. Have you checked if using the module works for you? It might not be specific to Nuxtent.

**Comment by alidcastano** [comment] 2017-07-22 00:56
Have you checked out the `env` property for Nuxt? https://nuxtjs.org/api/configuration-env/#the-env-property. 

Also the fallback wouldn't matter because you can pass your own custom option that overrides it (see: https://github.com/nuxt-community/nuxtent/blob/master/lib/module.js#L33)

e.g. 

```
module.exports = {
  api: {
    baseURL: (isProd) => isProd ? 'http://127.0.0.1:3000' : 'http://127.0.0.1:3000'
  }
}
```

**Comment by xemoka** [comment] 2017-07-22 01:02
Yep, it helps the CORS issue, but the defaults still present `localhost` as the content api endpoint and `127.0.0.1` as the webpack dev server location. 

Also setting a `HOST` or `PORT` environment variable does this too.

**Comment by alidcastano** [comment] 2017-07-22 01:19
Ah okay but that's not a problem with Nuxtent. All Nuxtent does is hook up to the existing `serverMiddleware` and use `axios` module to request that endpoint.

I'd open up the issue in the nuxt.js, or `@nuxtjs/axios` module repo and perhaps @pi0 will have a better answer.

**Comment by alidcastano** [comment] 2017-07-22 22:56
I'm going to close this issue, because, as described above, there doesn't seem to be much I can do on the Nuxtent end to resolve it. 

Feel free to open it back up or open up a new one if I'm mistaken.

**Closed by alidcastano** 2017-07-22 22:56 UTC

**Comment by xemoka** [comment] 2017-07-24 21:39
Well... I'm not sure if that's it. Sure it could be that the CORS problem is solvable upstream, but the windows issue is separate: there's two issues discussed in this post, 1) the cors problem, 2) the windows compatibility issue, unfortunately I haven't had more time to dig into that—or if the windows issue is also due to upstream. You're probably right, but I just can't see it yet. I'll have to give the axios module a try on it's own.

**Comment by alidcastano** [comment] 2017-07-24 21:57
Yeah, that's what I was going to recommend - give axios module a try by itself and get back to me.

**Comment by nathanchase** [comment] 2018-09-19 16:55
I have this issue with Nuxtent as well. It seems everyone on my team using Mac/Linux have no issues, but because I'm on a Windows machine, somehow things fail? With nuxtent removed, the app is fine, so there's definitely something going on here.
